### ISSUE TITLE
Upgrade to Swift 4

### ISSUE THREAD

**Issue by TetHat** [DougField-Development/Pump-Tracker#30]
I'm currently using Xcode 9 beta and after build it has a warning that says "Conversion to Swift 4 available." Haven't looked into what that does or anything yet, but would be good to look further into that and make the jump.

In order to do so before it's released, @beetdemguise we'll need to get you Xcode 9 beta from my dev account.

**Comment by beetdemguise** [comment]
To note: the linter supports Swift 3 out of the box. Upgrading to Swift 4 may break some of the rules; not stop-ship, but something to consider.

**Comment by TetHat** [comment]
Ya that makes sense. I think we can wait until it's officially out with that. My guess would be they're working on adding support for Swift 4 during the beta. Not really sure how many things we have written are changed in it either.

**Comment by TetHat** [comment]
SwiftLint GitHub page has Swift 4.x on the list for support versions. We should be good to upgrade.

**Comment by beetdemguise** [comment]
What about the Banner mod and the Events mod?

**Comment by TetHat** [comment]
When going through the upgrade process, it let's you choose which components of your app to upgrade to swift 4. So my guess is we would want to *not* upgrade those mods to swift 4, but just our own app code. Because if we upgrade those to 4, and then do a `pod update` or `pod install` it would basically just rewrite that upgrade anyway if they haven't already upgraded to 4. I can do some more looking into that, though.

**Comment by beetdemguise** [comment]
Hmm, I don't much like the idea of having a subset of our code base (whether it be our own code or 3rd party) running on a different version of Swift. I'd say if we do a full upgrade and the plugins still work, we can use Swift 4. Otherwise, we'd either have to upgrade/patch the failure spots or stick with Swift 3 until the maintainers update the modules.
