### ISSUE TITLE
Multiple consecutive clicks on a tab icon cause it to grow infinitely

### ISSUE THREAD

**Issue by beetdemguise** [DougField-Development/Pump-Tracker#35]

**Comment by TetHat** [comment]
Doesn't occur in my test on actual device. Could be a simulator bug. More testing to be done to confirm.

**Comment by TetHat** [comment]
Only location I've been able to replicate is the non-beta version of the simulator. Tested on multiple simulator devices in the beta version, as well as my phone itself and no issues. Closing.
